apiVersion : apps/v1
kind: Deployment
metadata:
  name: deployment-realstateapi
  labels:
    app.project.name: realstateapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realstateapi
  template:
    metadata:
      labels:
        app: realstateapi 
    spec:
      containers:
        - name: realstateapi 
          image: cesarag92/realestatelisting:latest
          ports:
            - containerPort: 8080
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3   
      imagePullSecrets:
        - name: dockerhub    